/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.algorithms.UI;

import com.mycompany.algorithms.Layers.BLL.BLLEvent;
import com.mycompany.algorithms.Layers.Entities.Event;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anibal
 */
public class frmRecursion extends javax.swing.JFrame {

    /**
     * Creates new form frmRecursion
     */
    public frmRecursion() {
        initComponents();
        cargarTitulosTabla();
    }

    private void cargarTitulosTabla() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("Year");
        model.addColumn("Month");
        model.addColumn("Day");
        model.addColumn("Team A");
        model.addColumn("Team B");
        model.addColumn("Sport");
        model.addColumn("Competition Name");
        model.addColumn("Competition Country");
        model.addColumn("Hour");

        tblEventsFoundedBetweenHours.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblFirstHour = new javax.swing.JLabel();
        lblSecondHour = new javax.swing.JLabel();
        txtSecondHour = new javax.swing.JTextField();
        txtFirstHour = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEventsFoundedBetweenHours = new javax.swing.JTable();
        btnCompareHours = new javax.swing.JButton();
        btnOrderingEvents = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFirstHour.setText("1 Hour");

        lblSecondHour.setText("2 Hour");

        tblEventsFoundedBetweenHours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEventsFoundedBetweenHours);

        btnCompareHours.setText("Compare Hours");
        btnCompareHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompareHoursActionPerformed(evt);
            }
        });

        btnOrderingEvents.setText("Ordering Events");
        btnOrderingEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderingEventsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstHour)
                    .addComponent(txtFirstHour, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSecondHour)
                    .addComponent(txtSecondHour, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnCompareHours)
                        .addGap(46, 46, 46)
                        .addComponent(btnOrderingEvents)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstHour)
                    .addComponent(lblSecondHour))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSecondHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompareHours)
                    .addComponent(btnOrderingEvents))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompareHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompareHoursActionPerformed
        String firstHour = txtFirstHour.getText();
        String secondHour = txtSecondHour.getText();

        LinkedList<Event> eventsInRange = BLLEvent.obtenerEventosEntreHoras(firstHour, secondHour);

        mostrarEventosEnTabla(eventsInRange);


    }//GEN-LAST:event_btnCompareHoursActionPerformed

    private void btnOrderingEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderingEventsActionPerformed
        // TODO add your handling code here:
        frmOrderingEvents frmOrderingEvents = new frmOrderingEvents();
        frmOrderingEvents.setVisible(true);
        frmOrderingEvents.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnOrderingEventsActionPerformed

    private void mostrarEventosEnTabla(LinkedList<Event> events) {
        DefaultTableModel model = (DefaultTableModel) tblEventsFoundedBetweenHours.getModel();

        model.setRowCount(0);

        for (Event event : events) {
            Object[] rowData = {
                event.getId(),
                event.getYear(),
                event.getMonth(),
                event.getDay(),
                event.getTeamA(),
                event.getTeamB(),
                event.getSport(),
                event.getCompetitionName(),
                event.getCompetitionCountry(),
                event.getHour()
            };
            model.addRow(rowData);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecursion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecursion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompareHours;
    private javax.swing.JButton btnOrderingEvents;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFirstHour;
    private javax.swing.JLabel lblSecondHour;
    private javax.swing.JTable tblEventsFoundedBetweenHours;
    private javax.swing.JTextField txtFirstHour;
    private javax.swing.JTextField txtSecondHour;
    // End of variables declaration//GEN-END:variables
}
